name: build
 
on:
  push:
  workflow_dispatch:
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    permissions:
      contents: read
      packages: write
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Get current date and set to environment variable
        run: echo "CURRENT_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV
 
      - name: Log in to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
   
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
   
      - name: Build all platforms images and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/docker-lineage-cicd:${{ env.CURRENT_DATE }}
            ${{ secrets.DOCKERHUB_USERNAME }}/docker-lineage-cicd:latest
